Use L:\CASSA\WIN\CASSAW.PJX
*Brow Fields NAME, HOMEDIR, TYPE, EXCLUDE, MAINPROG, SAVECODE, DEBUG, ENCRYPT, NOLOGO,;
*	CMNTSTYLE, COMMENTS, KEY
Brow Fields TYPE, KEY, name

*Brow Fiel ID, TIMESTAMP, OUTFILE, OBJREV, DEVINFO, CPID, OSTYPE, OSCREATOR, RESERVED1, RESERVED2,;
*	SCCDATA, LOCAL, CKVAL, SYMBOLS, OBJECT
Use
